version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo Installing dependencies...
      - dotnet restore
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 171139160358.dkr.ecr.eu-west-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - dotnet build -c Release
      - dotnet publish -c Release -o out
      - echo Build and push Docker image...
      - docker build -t backend-repo .
      - docker tag backend-repo:latest 171139160358.dkr.ecr.eu-west-2.amazonaws.com/backend-repo:latest
      - docker push 171139160358.dkr.ecr.eu-west-2.amazonaws.com/backend-repo:latest
      - echo Generating imagedefinitions.json...
      - printf '[{"name":"dotnetapp","imageUri":"171139160358.dkr.ecr.eu-west-2.amazonaws.com/backend-repo:latest"}]' > imagedefinitions.json
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - out/**
    - imagedefinitions.json
