version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 171139160358.dkr.ecr.eu-west-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t backend-repo .
      - docker tag backend-repo:latest 171139160358.dkr.ecr.eu-west-2.amazonaws.com/backend-repo:latest
      - docker push 171139160358.dkr.ecr.eu-west-2.amazonaws.com/backend-repo:latest
      - echo Generating imagedefinitions.json...
      - printf '[{"name":"backend-container","imageUri":"171139160358.dkr.ecr.eu-west-2.amazonaws.com/backend-repo:latest"}]' > imagedefinitions.json
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - imagedefinitions.json
